management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  config:
    import: "optional:configtree:/mnt/secrets/ccpay/"
  application:
    name: ServiceRequestCpoUpdateService
  main:
    allow-bean-definition-overriding: true
azure:
  application-insights:
    instrumentation-key: ${rpe.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}


amqp:
  host: ${AMQP_HOST:dummy}
  sharedAccessKeyName: ${AMQP_SHARED_ACCESS_KEY_NAME:dummy}
  jrd:
    topic: ${AMQP_TOPIC_NAME:dummy}
    sharedAccessKeyValue: ${AMQP_SHARED_ACCESS_KEY_VALUE:dummy}
    subscription: ${AMQP_SUBSCRIPTION:dummy}

idam:
  url: ${IDAM_API_URL:http://localhost:5000}
  serviceAccount:
    clientId: ${CPO_UPDATE_SERVICE_ACCOUNT_CLIENT_ID:dummy}
    clientSecret: ${CPO_UPDATE_ACCOUNT_CLIENT_SECRET:dummy}
    grantType:  ${CPO_UPDATE_ACCOUNT_GRANT_TYPE:dummy}
    username: ${CPO_UPDATE_ACCOUNT_USERNAME:dummy}
    password: ${CPO_UPDATE_ACCOUNT_PASSWORD:dummy}
    scope: ${CPO_UPDATE_ACCOUNT_SCOPE:dummy}
  s2s-auth:
    url: ${AUTH_PROVIDER_SERVICE_CLIENT_BASEURL:http://localhost:8085}
    totp_secret: ${OIDC_S2S_SECRET:dummy}
    microservice: ${OIDC_S2S_MICROSERVICE_NAME:dummy}
cpo:
  baseUrl: ${CPO_URL:http://localhost:3200}
  path: ${CPO_PATH:/case-payment-orders}

thread:
  count: ${THREAD_COUNT:4}
