management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  config:
    import: "optional:configtree:/mnt/secrets/ccpay/"
  application:
    name: ServiceRequestCpoUpdateService

azure:
  application-insights:
    instrumentation-key: ${rpe.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}


amqp:
  host: ${AMQP_HOST:dummy}
  sharedAccessKeyName: ${AMQP_SHARED_ACCESS_KEY_NAME:dummy}
  jrd:
    topic: ${AMQP_TOPIC_NAME:dummy}
    sharedAccessKeyValue: ${AMQP_SHARED_ACCESS_KEY_VALUE:dummy}
    subscription: ${AMQP_SUBSCRIPTION:dummy}
